name: Build MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [synchronize, opened, reopened, ready_for_review]
  workflow_dispatch:

concurrency: 
  group: build-MacOS-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2

      - name: Check architecture
        shell: bash
        run: |
          echo "The runner is of type $(uname -m)."
          if [ $(uname -m) != "x86_64" ] 
          then 
            echo "$(uname -m) detected. This test must be run on x86_64"
            exit -1
          fi
          exit 0

      - name: Install Packages
        run: |
          brew install flex bison autoconf automake libtool m4
          echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> /Users/runner/.bash_profile
          echo 'export PATH="/usr/local/opt/flex/bin:$PATH"' >> /Users/runner/.bash_profile
      - name: Build 
        uses: lukka/run-cmake@v2.5
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeAppendedArgs: >-
            -DVERIFYPN_Static=ON 
            -DVERIFYPN_MC_Simplification=OFF 
            -DBISON_EXECUTABLE=/usr/local/opt/bison/bin/bison 
            -DFLEX_EXECUTABLE=/usr/local/opt/flex/bin/flex
          cmakeBuildType: Release
          cmakeGenerator: UnixMakefiles
          buildDirectory: '${{runner.workspace}}/build'
          buildWithCMake: true
          buildWithCMakeArgs: -- -j$(sysctl -n hw.ncpu)
        env:
          CC: gcc-14
          CXX: g++-14
          
      - name: Upload artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: verifypn-osx64
          path: '${{runner.workspace}}/build/verifypn/bin/verifypn-osx64'
